# Generated by Django 4.0.6 on 2022-07-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgrab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlgrab',
            name='link',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='urlgrab',
            name='shorted_url',
            field=models.CharField(default='http://127.0.0.8:8000/shorter', max_length=300),
        ),
    ]
