# Generated by Django 4.0.6 on 2022-07-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlgrab', '0002_alter_urlgrab_link_alter_urlgrab_shorted_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlgrab',
            name='shorted_url',
        ),
        migrations.RemoveField(
            model_name='urlgrab',
            name='stored_time',
        ),
    ]
