# Generated by Django 4.0.6 on 2022-07-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgrab', '0004_alter_urlgrab_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlgrab',
            name='shorted_url',
            field=models.CharField(default='http://127.0.0.8:8000/shorter', max_length=300),
        ),
        migrations.AddField(
            model_name='urlgrab',
            name='stored_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
